/* The NULL and NOT NULL Operators 
We are creating a new table for this task*/
create table contact(
	id int generated by default as identity,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	email varchar(255) not null,
	phone varchar(15),
	primary key(id)
);